variables:
  GIT_STRATEGY: clone

stages:
  - test
  - build-release
  - test-pakage
  - publish
  
before_script:
  - $env:ORIGIN += 'https://{0}:{1}@git.auckland.dynabic.com/words-cloud/words-cloud-cpp.git' -f $env:GIT_CI_USER, $env:GIT_CI_PASS
  - $env:SDK_VERSION += ((Get-Date).AddMonths(1)).tostring("yy.M")
  
test-windows:
  stage: test
  script:
    - cmd /c 'docker build -f Dockerfile.windows -t aspose-words-cloud-cpp:windows .'
    - cmd /c 'runInDocker.windows.bat %WordsAppKey% %WordsAppSid% %WordsBaseUrl%'
  tags:
    - awcloud
  only:
    - branches
  except:
    - tmaster
  artifacts:
    expire_in: 1 hour
    reports:
      junit: out/*.xml

test-linux:
  stage: test
  script:
    - docker build -f Dockerfile.linux -t aspose-words-cloud-cpp:linux .
    - docker build -f Dockerfile.tests.linux -t aspose-words-cloud-cpp-tests:linux .
    - docker run --rm -v "$PWD/out:/out/" aspose-words-cloud-cpp-tests:linux bash aspose-words-cloud-cpp/scripts/runAll.sh $WordsAppKey $WordsAppSid $WordsBaseUrl
  tags:
    - awcloud-linux
  only:
    - branches
  except:
    - tmaster
  artifacts:
    expire_in: 1 hour
    reports:
      junit: out/*.xml

build-release:
  stage: build-release
  script:
    - Remove-Item -Path Aspose.Words.Cloud -Recurse -Force -ErrorAction Ignore
    - Get-ChildItem -Path sources | % {Copy-Item $_.fullname Aspose.Words.Cloud -Recurse -Force -Exclude (".*", "*.sh")}
    - git commit -am 'Create the release folder [ci skip]'
    - "git push $env:ORIGIN HEAD:master" 
  when: manual
  only:
    - tmaster
  tags:
    - awcloud

test-package-windows:
  stage: test-pakage
  script:
    - cmd /c 'docker build -f Dockerfile.windows -t aspose-words-cloud-cpp:windows .'
    - cmd /c 'testPackageInDocker.windows.bat %WordsAppKey% %WordsAppSid% %WordsBaseUrl%'
  tags:
    - awcloud-linux
  only:
    - tmaster
  artifacts:
    expire_in: 1 hour
    reports:
      junit: out/*.xml

test-package-linux:
  stage: test-pakage
  script:
    - docker build -f Dockerfile.linux -t aspose-words-cloud-cpp:linux .
    - docker build -f Dockerfile.tests.linux -t aspose-words-cloud-cpp-tests:linux .
    - docker run --rm -v "$PWD/out:/out/" aspose-words-cloud-cpp-tests:linux bash aspose-words-cloud-cpp/scripts/testPackage.sh $WordsAppKey $WordsAppSid $WordsBaseUrl
  tags:
    - awcloud
  only:
    - tmaster
  artifacts:
    expire_in: 1 hour
    reports:
      junit: out/*.xml    
    
publish-lib:
  stage: publish
  only:
    - tmaster
  script:
    - git rebase release
    - git checkout release
    - git merge tmaster
    - 'git push $env:ORIGIN HEAD:release'
    - 'git tag -a v$env:SDK_VERSION -m "Aspose.Words.Cloud SDK for C++ version $env:SDK_VERSION"'
    - "git push $env:ORIGIN v$env:SDK_VERSION"

  tags:
    - awcloud
