variables:
  GIT_STRATEGY: clone

stages:
  - test
  
test-windows:
  stage: test
  tags:
    - awcloud
  only:
    - branches
  except:
    - master
  script:
    - cmd /c 'docker build -f Dockerfile.windows -t aspose-words-cloud-cpp:windows .'
    - cmd /c 'runInDocker.windows.bat %WordsAppKey% %WordsAppSid% %WordsBaseUrl%'
  artifacts:
    expire_in: 1 hour
    reports:
      junit: out/*.xml

test-linux:
  stage: test
  tags:
    - awcloud-linux
  only:
    - branches
  except:
    - master
  script:
    - docker build -f Dockerfile.linux -t aspose-words-cloud-cpp:linux .
    - docker build -f Dockerfile.tests.linux -t aspose-words-cloud-cpp-tests:linux .
    - docker run --rm -v "$PWD/out:/out/" aspose-words-cloud-cpp-tests:linux bash aspose-words-cloud-cpp/scripts/runAll.sh $WordsAppKey $WordsAppSid $WordsBaseUrl
  artifacts:
    expire_in: 1 hour
    reports:
      junit: out/*.xml