variables:
  GIT_STRATEGY: clone

windows-test:
  script:
    - cmd /c 'docker build -f Dockerfile.windows -t aspose-words-cloud-cpp:windows .'
    - cmd /c 'runInDocker.windows.bat %WordsAppKey% %WordsAppSid% %WordsBaseUrl%'
  tags:
    - awcloud
  artifacts:
    expire_in: 1 hour
    reports:
      junit: out/*.xml

linux-test:
  script:
    - docker build -f Dockerfile.linux -t aspose-words-cloud-cpp:linux .
    - docker build -f Dockerfile.tests.linux -t aspose-words-cloud-cpp-tests:linux .
    - docker run --rm -v "$PWD/out:/out/" aspose-words-cloud-cpp-tests:linux bash aspose-words-cloud-cpp/scripts/runAll.sh $WordsAppKey $WordsAppSid $WordsBaseUrl
  tags:
    - awcloud-linux
  artifacts:
    expire_in: 1 hour
    reports:
      junit: out/*.xml