variables:
  GIT_STRATEGY: clone

stages:
  - build-release
  - test-pakage
 
build-release:
  stage: build-release
  tags:
    - awcloud
  script:
    - Remove-Item -Path Aspose.Words.Cloud -Recurse -Force -ErrorAction Ignore
    - Get-ChildItem -Path sources | % {Copy-Item $_.fullname Aspose.Words.Cloud -Recurse -Force -Exclude (".*", "*.sh")}
    - Copy-Item Aspose.Words.Cloud app
    - Copy-Item thirdparty app
    - Copy-Item tests app
  artifacts:
    paths:
      - app/

test-package-windows:
  stage: test-pakage
  tags:
    - awcloud
  script:
    - cmd /c 'docker build -f Dockerfile.windows -t aspose-words-cloud-cpp:windows .'
    - cmd /c 'testPackageInDocker.windows.bat %WordsAppKey% %WordsAppSid% %WordsBaseUrl%'

test-package-linux:
  stage: test-pakage
  tags:
    - awcloud-linux
  script:
    - docker build -f Dockerfile.linux -t aspose-words-cloud-cpp:linux .
    - docker build -f Dockerfile.tests.linux -t aspose-words-cloud-cpp-tests:linux .
    - docker run --rm -v "$PWD/out:/out/" aspose-words-cloud-cpp-tests:linux bash aspose-words-cloud-cpp/scripts/testPackage.sh $WordsAppKey $WordsAppSid $WordsBaseUrl