/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * AsposeResponse.h
 *
 * Base class for all responses.
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_AsposeResponse_H_
#define IO_SWAGGER_CLIENT_MODEL_AsposeResponse_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Base class for all responses.
/// </summary>
class  AsposeResponse
    : public ModelBase
{
public:
    AsposeResponse();
    virtual ~AsposeResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// AsposeResponse members

    /// <summary>
    /// Response status code.
    /// </summary>
    int32_t getCode() const;
        void setCode(int32_t value);
    /// <summary>
    /// Response status.
    /// </summary>
    utility::string_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(utility::string_t value);

protected:
    int32_t m_Code;
        utility::string_t m_Status;
    bool m_StatusIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_AsposeResponse_H_ */
