/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * BookmarksOutlineLevelData.h
 *
 * container class for individual bookmarks outline level
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_BookmarksOutlineLevelData_H_
#define IO_SWAGGER_CLIENT_MODEL_BookmarksOutlineLevelData_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// container class for individual bookmarks outline level
/// </summary>
class  BookmarksOutlineLevelData
    : public ModelBase
{
public:
    BookmarksOutlineLevelData();
    virtual ~BookmarksOutlineLevelData();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// BookmarksOutlineLevelData members

    /// <summary>
    /// Specify the bookmark&#39;s name
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(utility::string_t value);
    /// <summary>
    /// Specify the bookmark&#39;s level
    /// </summary>
    int32_t getBookmarksOutlineLevel() const;
        void setBookmarksOutlineLevel(int32_t value);

protected:
    utility::string_t m_Name;
    bool m_NameIsSet;
    int32_t m_BookmarksOutlineLevel;
    };

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_BookmarksOutlineLevelData_H_ */
