/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Bookmarks.h
 *
 * Represents an array of bookmarks.
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_Bookmarks_H_
#define IO_SWAGGER_CLIENT_MODEL_Bookmarks_H_


#include "Bookmark.h"
#include "LinkElement.h"
#include <vector>
#include "WordsApiLink.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Represents an array of bookmarks.
/// </summary>
class  Bookmarks
    : public LinkElement
{
public:
    Bookmarks();
    virtual ~Bookmarks();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Bookmarks members

    /// <summary>
    /// Array of bookmarks.
    /// </summary>
    std::vector<std::shared_ptr<Bookmark>>& getBookmarkList();
    bool bookmarkListIsSet() const;
    void unsetBookmarkList();
    void setBookmarkList(std::vector<std::shared_ptr<Bookmark>> value);

protected:
    std::vector<std::shared_ptr<Bookmark>> m_BookmarkList;
    bool m_BookmarkListIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_Bookmarks_H_ */
