/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * BordersResponse.h
 *
 * This response should be returned by the service when handling: GET {nodeWithBorders}/borders.
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_BordersResponse_H_
#define IO_SWAGGER_CLIENT_MODEL_BordersResponse_H_


#include "AsposeResponse.h"
#include "BordersCollection.h"
#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// This response should be returned by the service when handling: GET {nodeWithBorders}/borders.
/// </summary>
class  BordersResponse
    : public AsposeResponse
{
public:
    BordersResponse();
    virtual ~BordersResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// BordersResponse members

    /// <summary>
    /// Table.
    /// </summary>
    std::shared_ptr<BordersCollection> getBorders() const;
    bool bordersIsSet() const;
    void unsetBorders();
    void setBorders(std::shared_ptr<BordersCollection> value);

protected:
    std::shared_ptr<BordersCollection> m_Borders;
    bool m_BordersIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_BordersResponse_H_ */
