/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * DocumentPosition.h
 *
 * Represents a position in the document tree.
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_DocumentPosition_H_
#define IO_SWAGGER_CLIENT_MODEL_DocumentPosition_H_


#include "../ModelBase.h"

#include "NodeLink.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Represents a position in the document tree.
/// </summary>
class  DocumentPosition
    : public ModelBase
{
public:
    DocumentPosition();
    virtual ~DocumentPosition();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// DocumentPosition members

    /// <summary>
    /// Link to  node.
    /// </summary>
    std::shared_ptr<NodeLink> getNode() const;
    bool nodeIsSet() const;
    void unsetNode();
    void setNode(std::shared_ptr<NodeLink> value);
    /// <summary>
    /// Offset into the node.
    /// </summary>
    int32_t getOffset() const;
    bool offsetIsSet() const;
    void unsetOffset();
    void setOffset(int32_t value);

protected:
    std::shared_ptr<NodeLink> m_Node;
    bool m_NodeIsSet;
    int32_t m_Offset;
    bool m_OffsetIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_DocumentPosition_H_ */
