/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * DocumentPropertiesResponse.h
 *
 * This response should be returned by the service when handling:  GET /documentProperties.
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_DocumentPropertiesResponse_H_
#define IO_SWAGGER_CLIENT_MODEL_DocumentPropertiesResponse_H_


#include "AsposeResponse.h"
#include <cpprest/details/basic_types.h>
#include "DocumentProperties.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// This response should be returned by the service when handling:  GET /documentProperties.
/// </summary>
class  DocumentPropertiesResponse
    : public AsposeResponse
{
public:
    DocumentPropertiesResponse();
    virtual ~DocumentPropertiesResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// DocumentPropertiesResponse members

    /// <summary>
    /// Collection of document properties.
    /// </summary>
    std::shared_ptr<DocumentProperties> getDocumentProperties() const;
    bool documentPropertiesIsSet() const;
    void unsetDocumentProperties();
    void setDocumentProperties(std::shared_ptr<DocumentProperties> value);

protected:
    std::shared_ptr<DocumentProperties> m_DocumentProperties;
    bool m_DocumentPropertiesIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_DocumentPropertiesResponse_H_ */
