/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "DocumentEntryList.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

DocumentEntryList::DocumentEntryList()
{
    m_DocumentEntriesIsSet = false;
}

DocumentEntryList::~DocumentEntryList()
{
}

void DocumentEntryList::validate()
{
    // TODO: implement validation
}

web::json::value DocumentEntryList::toJson() const
{
    web::json::value val = web::json::value::object();

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_DocumentEntries )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[utility::conversions::to_string_t("DocumentEntries")] = web::json::value::array(jsonArray);
        }
    }

    return val;
}

void DocumentEntryList::fromJson(web::json::value& val)
{
    {
        m_DocumentEntries.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(utility::conversions::to_string_t("DocumentEntries")))
        {
        for( auto& item : val[utility::conversions::to_string_t("DocumentEntries")].as_array() )
        {
            if(item.is_null())
            {
                m_DocumentEntries.push_back( std::shared_ptr<DocumentEntry>(nullptr) );
            }
            else
            {
                std::shared_ptr<DocumentEntry> newItem(new DocumentEntry());
                newItem->fromJson(item);
                m_DocumentEntries.push_back( newItem );
            }
        }
        }
    }
}

void DocumentEntryList::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_DocumentEntries )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("DocumentEntries"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
        }
    }
}

void DocumentEntryList::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    {
        m_DocumentEntries.clear();
        if(multipart->hasContent(utility::conversions::to_string_t("DocumentEntries")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("DocumentEntries"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_DocumentEntries.push_back( std::shared_ptr<DocumentEntry>(nullptr) );
            }
            else
            {
                std::shared_ptr<DocumentEntry> newItem(new DocumentEntry());
                newItem->fromJson(item);
                m_DocumentEntries.push_back( newItem );
            }
        }
        }
    }
}

std::vector<std::shared_ptr<DocumentEntry>>& DocumentEntryList::getDocumentEntries()
{
    return m_DocumentEntries;
}

void DocumentEntryList::setDocumentEntries(std::vector<std::shared_ptr<DocumentEntry>> value)
{
    m_DocumentEntries = value;
    m_DocumentEntriesIsSet = true;
}
bool DocumentEntryList::documentEntriesIsSet() const
{
    return m_DocumentEntriesIsSet;
}

void DocumentEntryList::unsetDocumentEntries()
{
    m_DocumentEntriesIsSet = false;
}

}
}
}
}

