/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * DocumentProperty.h
 *
 * Words document property DTO.
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_DocumentProperty_H_
#define IO_SWAGGER_CLIENT_MODEL_DocumentProperty_H_


#include <cpprest/details/basic_types.h>
#include "LinkElement.h"
#include "WordsApiLink.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Words document property DTO.
/// </summary>
class  DocumentProperty
    : public LinkElement
{
public:
    DocumentProperty();
    virtual ~DocumentProperty();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// DocumentProperty members

    /// <summary>
    /// Flag indicates whether the property is built-in or not. If true the property is built-in, if false the property is custom.
    /// </summary>
    bool isBuiltIn() const;
    bool builtInIsSet() const;
    void unsetBuiltIn();
    void setBuiltIn(bool value);
    /// <summary>
    /// Name of the document property.
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(utility::string_t value);
    /// <summary>
    /// string value of the document property. 
    /// </summary>
    utility::string_t getValue() const;
    bool valueIsSet() const;
    void unsetValue();
    void setValue(utility::string_t value);

protected:
    bool m_BuiltIn;
    bool m_BuiltInIsSet;
    utility::string_t m_Name;
    bool m_NameIsSet;
    utility::string_t m_Value;
    bool m_ValueIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_DocumentProperty_H_ */
