/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * DrawingObjectsResponse.h
 *
 * This response should be returned by the service when handling:  GET /drawingObjects.
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_DrawingObjectsResponse_H_
#define IO_SWAGGER_CLIENT_MODEL_DrawingObjectsResponse_H_


#include "AsposeResponse.h"
#include "DrawingObjectCollection.h"
#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// This response should be returned by the service when handling:  GET /drawingObjects.
/// </summary>
class  DrawingObjectsResponse
    : public AsposeResponse
{
public:
    DrawingObjectsResponse();
    virtual ~DrawingObjectsResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// DrawingObjectsResponse members

    /// <summary>
    /// Collection of drawing objects.
    /// </summary>
    std::shared_ptr<DrawingObjectCollection> getDrawingObjects() const;
    bool drawingObjectsIsSet() const;
    void unsetDrawingObjects();
    void setDrawingObjects(std::shared_ptr<DrawingObjectCollection> value);

protected:
    std::shared_ptr<DrawingObjectCollection> m_DrawingObjects;
    bool m_DrawingObjectsIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_DrawingObjectsResponse_H_ */
