/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * FieldsResponse.h
 *
 * This response should be returned by the service when handling: GET http://api.aspose.com/v1.1/words/Test.doc/{nodePath}/fields
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_FieldsResponse_H_
#define IO_SWAGGER_CLIENT_MODEL_FieldsResponse_H_


#include "AsposeResponse.h"
#include "FieldCollection.h"
#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// This response should be returned by the service when handling: GET http://api.aspose.com/v1.1/words/Test.doc/{nodePath}/fields
/// </summary>
class  FieldsResponse
    : public AsposeResponse
{
public:
    FieldsResponse();
    virtual ~FieldsResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// FieldsResponse members

    /// <summary>
    /// Collection of fields.
    /// </summary>
    std::shared_ptr<FieldCollection> getFields() const;
    bool fieldsIsSet() const;
    void unsetFields();
    void setFields(std::shared_ptr<FieldCollection> value);

protected:
    std::shared_ptr<FieldCollection> m_Fields;
    bool m_FieldsIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_FieldsResponse_H_ */
