/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * FontInfo.h
 *
 * Font info
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_FontInfo_H_
#define IO_SWAGGER_CLIENT_MODEL_FontInfo_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Font info
/// </summary>
class  FontInfo
    : public ModelBase
{
public:
    FontInfo();
    virtual ~FontInfo();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// FontInfo members

    /// <summary>
    /// Family name of the font.
    /// </summary>
    utility::string_t getFontFamilyName() const;
    bool fontFamilyNameIsSet() const;
    void unsetFontFamilyName();
    void setFontFamilyName(utility::string_t value);
    /// <summary>
    /// Full name of the font.
    /// </summary>
    utility::string_t getFullFontName() const;
    bool fullFontNameIsSet() const;
    void unsetFullFontName();
    void setFullFontName(utility::string_t value);
    /// <summary>
    /// Version string of the font.
    /// </summary>
    utility::string_t getVersion() const;
    bool versionIsSet() const;
    void unsetVersion();
    void setVersion(utility::string_t value);
    /// <summary>
    /// Path to the font file if any.
    /// </summary>
    utility::string_t getFilePath() const;
    bool filePathIsSet() const;
    void unsetFilePath();
    void setFilePath(utility::string_t value);

protected:
    utility::string_t m_FontFamilyName;
    bool m_FontFamilyNameIsSet;
    utility::string_t m_FullFontName;
    bool m_FullFontNameIsSet;
    utility::string_t m_Version;
    bool m_VersionIsSet;
    utility::string_t m_FilePath;
    bool m_FilePathIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_FontInfo_H_ */
