/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * FontResponse.h
 *
 * This response should be returned by the service when handling: GET http://api.aspose.com/v1.1/words/Test.doc/paragraphs/{0}/runs/{1}/font 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_FontResponse_H_
#define IO_SWAGGER_CLIENT_MODEL_FontResponse_H_


#include "AsposeResponse.h"
#include <cpprest/details/basic_types.h>
#include "Font.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// This response should be returned by the service when handling: GET http://api.aspose.com/v1.1/words/Test.doc/paragraphs/{0}/runs/{1}/font 
/// </summary>
class  FontResponse
    : public AsposeResponse
{
public:
    FontResponse();
    virtual ~FontResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// FontResponse members

    /// <summary>
    /// Font
    /// </summary>
    std::shared_ptr<Font> getFont() const;
    bool fontIsSet() const;
    void unsetFont();
    void setFont(std::shared_ptr<Font> value);

protected:
    std::shared_ptr<Font> m_Font;
    bool m_FontIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_FontResponse_H_ */
