/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * FootnoteLink.h
 *
 * Footnote link.
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_FootnoteLink_H_
#define IO_SWAGGER_CLIENT_MODEL_FootnoteLink_H_


#include "NodeLink.h"
#include <cpprest/details/basic_types.h>
#include "WordsApiLink.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Footnote link.
/// </summary>
class  FootnoteLink
    : public NodeLink
{
public:
    FootnoteLink();
    virtual ~FootnoteLink();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// FootnoteLink members


protected:
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_FootnoteLink_H_ */
