/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * FootnoteResponse.h
 *
 * This response should be returned by the service when handling: GET http://api.aspose.com/v1.1/words/Test.doc/footnote/0 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_FootnoteResponse_H_
#define IO_SWAGGER_CLIENT_MODEL_FootnoteResponse_H_


#include "AsposeResponse.h"
#include <cpprest/details/basic_types.h>
#include "Footnote.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// This response should be returned by the service when handling: GET http://api.aspose.com/v1.1/words/Test.doc/footnote/0 
/// </summary>
class  FootnoteResponse
    : public AsposeResponse
{
public:
    FootnoteResponse();
    virtual ~FootnoteResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// FootnoteResponse members

    /// <summary>
    /// Footnote information
    /// </summary>
    std::shared_ptr<Footnote> getFootnote() const;
    bool footnoteIsSet() const;
    void unsetFootnote();
    void setFootnote(std::shared_ptr<Footnote> value);

protected:
    std::shared_ptr<Footnote> m_Footnote;
    bool m_FootnoteIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_FootnoteResponse_H_ */
