/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * FormFieldResponse.h
 *
 * This response should be returned by the service when handling: GET http://api.aspose.com/v1.1/words/Test.doc/paragraphs/{0}/formfields/{1} 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_FormFieldResponse_H_
#define IO_SWAGGER_CLIENT_MODEL_FormFieldResponse_H_


#include "AsposeResponse.h"
#include "FormField.h"
#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// This response should be returned by the service when handling: GET http://api.aspose.com/v1.1/words/Test.doc/paragraphs/{0}/formfields/{1} 
/// </summary>
class  FormFieldResponse
    : public AsposeResponse
{
public:
    FormFieldResponse();
    virtual ~FormFieldResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// FormFieldResponse members

    /// <summary>
    /// Field information
    /// </summary>
    std::shared_ptr<FormField> getFormField() const;
    bool formFieldIsSet() const;
    void unsetFormField();
    void setFormField(std::shared_ptr<FormField> value);

protected:
    std::shared_ptr<FormField> m_FormField;
    bool m_FormFieldIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_FormFieldResponse_H_ */
