/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * FormFieldDropDown.h
 *
 * FormField dropdownlist element
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_FormFieldDropDown_H_
#define IO_SWAGGER_CLIENT_MODEL_FormFieldDropDown_H_


#include "FormField.h"
#include <cpprest/details/basic_types.h>
#include <vector>
#include "WordsApiLink.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// FormField dropdownlist element
/// </summary>
class  FormFieldDropDown
    : public FormField
{
public:
    FormFieldDropDown();
    virtual ~FormFieldDropDown();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// FormFieldDropDown members

    /// <summary>
    /// Provides access to the items of a dropdown form field.
    /// </summary>
    std::vector<utility::string_t>& getDropDownItems();
    bool dropDownItemsIsSet() const;
    void unsetDropDownItems();
    void setDropDownItems(std::vector<utility::string_t> value);
    /// <summary>
    /// Gets or sets the index specifying the currently selected item in a dropdown form field.
    /// </summary>
    int32_t getDropDownSelectedIndex() const;
    bool dropDownSelectedIndexIsSet() const;
    void unsetDropDownSelectedIndex();
    void setDropDownSelectedIndex(int32_t value);

protected:
    std::vector<utility::string_t> m_DropDownItems;
    bool m_DropDownItemsIsSet;
    int32_t m_DropDownSelectedIndex;
    bool m_DropDownSelectedIndexIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_FormFieldDropDown_H_ */
