/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Hyperlinks.h
 *
 * Collection of .
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_Hyperlinks_H_
#define IO_SWAGGER_CLIENT_MODEL_Hyperlinks_H_


#include "Hyperlink.h"
#include "LinkElement.h"
#include <vector>
#include "WordsApiLink.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Collection of .
/// </summary>
class  Hyperlinks
    : public LinkElement
{
public:
    Hyperlinks();
    virtual ~Hyperlinks();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Hyperlinks members

    /// <summary>
    /// Array of .
    /// </summary>
    std::vector<std::shared_ptr<Hyperlink>>& getHyperlinkList();
    bool hyperlinkListIsSet() const;
    void unsetHyperlinkList();
    void setHyperlinkList(std::vector<std::shared_ptr<Hyperlink>> value);

protected:
    std::vector<std::shared_ptr<Hyperlink>> m_HyperlinkList;
    bool m_HyperlinkListIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_Hyperlinks_H_ */
