/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * HyperlinksResponse.h
 *
 * This response should be returned by the service when handling:  GET /{name}/hyperlinks .
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_HyperlinksResponse_H_
#define IO_SWAGGER_CLIENT_MODEL_HyperlinksResponse_H_


#include "Hyperlinks.h"
#include "AsposeResponse.h"
#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// This response should be returned by the service when handling:  GET /{name}/hyperlinks .
/// </summary>
class  HyperlinksResponse
    : public AsposeResponse
{
public:
    HyperlinksResponse();
    virtual ~HyperlinksResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// HyperlinksResponse members

    /// <summary>
    /// Collection of hyperlinks.
    /// </summary>
    std::shared_ptr<Hyperlinks> getHyperlinks() const;
    bool hyperlinksIsSet() const;
    void unsetHyperlinks();
    void setHyperlinks(std::shared_ptr<Hyperlinks> value);

protected:
    std::shared_ptr<Hyperlinks> m_Hyperlinks;
    bool m_HyperlinksIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_HyperlinksResponse_H_ */
