/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Hyperlink.h
 *
 * Hyperlink element.
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_Hyperlink_H_
#define IO_SWAGGER_CLIENT_MODEL_Hyperlink_H_


#include <cpprest/details/basic_types.h>
#include "LinkElement.h"
#include "WordsApiLink.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Hyperlink element.
/// </summary>
class  Hyperlink
    : public LinkElement
{
public:
    Hyperlink();
    virtual ~Hyperlink();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Hyperlink members

    /// <summary>
    /// Hypelink&#39;s display text
    /// </summary>
    utility::string_t getDisplayText() const;
    bool displayTextIsSet() const;
    void unsetDisplayText();
    void setDisplayText(utility::string_t value);
    /// <summary>
    /// Value
    /// </summary>
    utility::string_t getValue() const;
    bool valueIsSet() const;
    void unsetValue();
    void setValue(utility::string_t value);

protected:
    utility::string_t m_DisplayText;
    bool m_DisplayTextIsSet;
    utility::string_t m_Value;
    bool m_ValueIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_Hyperlink_H_ */
