/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "LinkElement.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

LinkElement::LinkElement()
{
    m_LinkIsSet = false;
}

LinkElement::~LinkElement()
{
}

void LinkElement::validate()
{
    // TODO: implement validation
}

web::json::value LinkElement::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_LinkIsSet)
    {
        val[utility::conversions::to_string_t("link")] = ModelBase::toJson(m_Link);
    }

    return val;
}

void LinkElement::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("link")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("link")];
        if(!fieldValue.is_null())
        {
            std::shared_ptr<WordsApiLink> newItem(new WordsApiLink());
            newItem->fromJson(fieldValue);
            setLink( newItem );
        }
    }
}

void LinkElement::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_LinkIsSet)
    {
        if (m_Link.get())
        {
            m_Link->toMultipart(multipart, utility::conversions::to_string_t("link."));
        }
        
    }
}

void LinkElement::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("link")))
    {
        if(multipart->hasContent(utility::conversions::to_string_t("link")))
        {
            std::shared_ptr<WordsApiLink> newItem(new WordsApiLink());
            newItem->fromMultiPart(multipart, utility::conversions::to_string_t("link."));
            setLink( newItem );
        }
    }
}

std::shared_ptr<WordsApiLink> LinkElement::getLink() const
{
    return m_Link;
}


void LinkElement::setLink(std::shared_ptr<WordsApiLink> value)
{
    m_Link = value;
    m_LinkIsSet = true;
}
bool LinkElement::linkIsSet() const
{
    return m_LinkIsSet;
}

void LinkElement::unsetLink()
{
    m_LinkIsSet = false;
}

}
}
}
}

