/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * LinkElement.h
 *
 * Reference to document.
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_LinkElement_H_
#define IO_SWAGGER_CLIENT_MODEL_LinkElement_H_


#include "../ModelBase.h"

#include "WordsApiLink.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Reference to document.
/// </summary>
class  LinkElement
    : public ModelBase
{
public:
    LinkElement();
    virtual ~LinkElement();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// LinkElement members

    /// <summary>
    /// Link to the document.
    /// </summary>
    std::shared_ptr<WordsApiLink> getLink() const;
    bool linkIsSet() const;
    void unsetLink();
    void setLink(std::shared_ptr<WordsApiLink> value);

protected:
    std::shared_ptr<WordsApiLink> m_Link;
    bool m_LinkIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_LinkElement_H_ */
