/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * MhtmlSaveOptionsData.h
 *
 * Container class for mhtml save options.
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_MhtmlSaveOptionsData_H_
#define IO_SWAGGER_CLIENT_MODEL_MhtmlSaveOptionsData_H_


#include <cpprest/details/basic_types.h>
#include "HtmlSaveOptionsData.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Container class for mhtml save options.
/// </summary>
class  MhtmlSaveOptionsData
    : public HtmlSaveOptionsData
{
public:
    MhtmlSaveOptionsData();
    virtual ~MhtmlSaveOptionsData();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// MhtmlSaveOptionsData members

    /// <summary>
    /// Specifies whether to use CID (Content-ID) URLs to reference resources (images, fonts, CSS) included in MHTML documents. Default value is false.             
    /// </summary>
    bool isExportCidUrlsForMhtmlResources() const;
    bool exportCidUrlsForMhtmlResourcesIsSet() const;
    void unsetExportCidUrlsForMhtmlResources();
    void setExportCidUrlsForMhtmlResources(bool value);

protected:
    bool m_ExportCidUrlsForMhtmlResources;
    bool m_ExportCidUrlsForMhtmlResourcesIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_MhtmlSaveOptionsData_H_ */
