/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * PclSaveOptionsData.h
 *
 * Container class for pcl save options
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_PclSaveOptionsData_H_
#define IO_SWAGGER_CLIENT_MODEL_PclSaveOptionsData_H_


#include "MetafileRenderingOptionsData.h"
#include "FixedPageSaveOptionsData.h"
#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Container class for pcl save options
/// </summary>
class  PclSaveOptionsData
    : public FixedPageSaveOptionsData
{
public:
    PclSaveOptionsData();
    virtual ~PclSaveOptionsData();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// PclSaveOptionsData members

    /// <summary>
    /// Name of the font that will be used if no expected font is found in printer and built-in fonts collections.
    /// </summary>
    utility::string_t getFalllbackFontName() const;
    bool falllbackFontNameIsSet() const;
    void unsetFalllbackFontName();
    void setFalllbackFontName(utility::string_t value);
    /// <summary>
    /// Gets or sets a value determining whether or not complex transformed elements should be rasterized before saving to PCL document.  Default is true.
    /// </summary>
    bool isRasterizeTransformedElements() const;
    bool rasterizeTransformedElementsIsSet() const;
    void unsetRasterizeTransformedElements();
    void setRasterizeTransformedElements(bool value);

protected:
    utility::string_t m_FalllbackFontName;
    bool m_FalllbackFontNameIsSet;
    bool m_RasterizeTransformedElements;
    bool m_RasterizeTransformedElementsIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_PclSaveOptionsData_H_ */
