/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "ProtectionData.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

ProtectionData::ProtectionData()
{
    m_ProtectionType = utility::conversions::to_string_t("");
    m_ProtectionTypeIsSet = false;
}

ProtectionData::~ProtectionData()
{
}

void ProtectionData::validate()
{
    // TODO: implement validation
}

web::json::value ProtectionData::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_ProtectionTypeIsSet)
    {
        val[utility::conversions::to_string_t("ProtectionType")] = ModelBase::toJson(m_ProtectionType);
    }

    return val;
}

void ProtectionData::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("ProtectionType")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("ProtectionType")];
        if(!fieldValue.is_null())
        {
            setProtectionType(ModelBase::stringFromJson(fieldValue));
        }
    }
}

void ProtectionData::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_ProtectionTypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("ProtectionType"), m_ProtectionType));
        
    }
}

void ProtectionData::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("ProtectionType")))
    {
        setProtectionType(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("ProtectionType"))));
    }
}

utility::string_t ProtectionData::getProtectionType() const
{
    return m_ProtectionType;
}


void ProtectionData::setProtectionType(utility::string_t value)
{
    m_ProtectionType = value;
    m_ProtectionTypeIsSet = true;
}
bool ProtectionData::protectionTypeIsSet() const
{
    return m_ProtectionTypeIsSet;
}

void ProtectionData::unsetProtectionType()
{
    m_ProtectionTypeIsSet = false;
}

}
}
}
}

