/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "ProtectionDataResponse.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

ProtectionDataResponse::ProtectionDataResponse()
{
    m_DocumentLinkIsSet = false;
    m_ProtectionDataIsSet = false;
}

ProtectionDataResponse::~ProtectionDataResponse()
{
}

void ProtectionDataResponse::validate()
{
    // TODO: implement validation
}

web::json::value ProtectionDataResponse::toJson() const
{
    web::json::value val = this->AsposeResponse::toJson();

    if(m_DocumentLinkIsSet)
    {
        val[utility::conversions::to_string_t("DocumentLink")] = ModelBase::toJson(m_DocumentLink);
    }
    if(m_ProtectionDataIsSet)
    {
        val[utility::conversions::to_string_t("ProtectionData")] = ModelBase::toJson(m_ProtectionData);
    }

    return val;
}

void ProtectionDataResponse::fromJson(web::json::value& val)
{
    this->AsposeResponse::fromJson(val);

    if(val.has_field(utility::conversions::to_string_t("DocumentLink")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("DocumentLink")];
        if(!fieldValue.is_null())
        {
            std::shared_ptr<FileLink> newItem(new FileLink());
            newItem->fromJson(fieldValue);
            setDocumentLink( newItem );
        }
    }
    if(val.has_field(utility::conversions::to_string_t("ProtectionData")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("ProtectionData")];
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ProtectionData> newItem(new ProtectionData());
            newItem->fromJson(fieldValue);
            setProtectionData( newItem );
        }
    }
}

void ProtectionDataResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("Code"), m_Code));
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("Status"), m_Status));
        
    }
    if(m_DocumentLinkIsSet)
    {
        if (m_DocumentLink.get())
        {
            m_DocumentLink->toMultipart(multipart, utility::conversions::to_string_t("DocumentLink."));
        }
        
    }
    if(m_ProtectionDataIsSet)
    {
        if (m_ProtectionData.get())
        {
            m_ProtectionData->toMultipart(multipart, utility::conversions::to_string_t("ProtectionData."));
        }
        
    }
}

void ProtectionDataResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setCode(ModelBase::int32_tFromHttpContent(multipart->getContent(utility::conversions::to_string_t("Code"))));
    if(multipart->hasContent(utility::conversions::to_string_t("Status")))
    {
        setStatus(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("Status"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("DocumentLink")))
    {
        if(multipart->hasContent(utility::conversions::to_string_t("DocumentLink")))
        {
            std::shared_ptr<FileLink> newItem(new FileLink());
            newItem->fromMultiPart(multipart, utility::conversions::to_string_t("DocumentLink."));
            setDocumentLink( newItem );
        }
    }
    if(multipart->hasContent(utility::conversions::to_string_t("ProtectionData")))
    {
        if(multipart->hasContent(utility::conversions::to_string_t("ProtectionData")))
        {
            std::shared_ptr<ProtectionData> newItem(new ProtectionData());
            newItem->fromMultiPart(multipart, utility::conversions::to_string_t("ProtectionData."));
            setProtectionData( newItem );
        }
    }
}

std::shared_ptr<FileLink> ProtectionDataResponse::getDocumentLink() const
{
    return m_DocumentLink;
}


void ProtectionDataResponse::setDocumentLink(std::shared_ptr<FileLink> value)
{
    m_DocumentLink = value;
    m_DocumentLinkIsSet = true;
}
bool ProtectionDataResponse::documentLinkIsSet() const
{
    return m_DocumentLinkIsSet;
}

void ProtectionDataResponse::unsetDocumentLink()
{
    m_DocumentLinkIsSet = false;
}

std::shared_ptr<ProtectionData> ProtectionDataResponse::getProtectionData() const
{
    return m_ProtectionData;
}


void ProtectionDataResponse::setProtectionData(std::shared_ptr<ProtectionData> value)
{
    m_ProtectionData = value;
    m_ProtectionDataIsSet = true;
}
bool ProtectionDataResponse::protectionDataIsSet() const
{
    return m_ProtectionDataIsSet;
}

void ProtectionDataResponse::unsetProtectionData()
{
    m_ProtectionDataIsSet = false;
}

}
}
}
}

