/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SearchResultsCollection.h
 *
 * Collection of search results.
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_SearchResultsCollection_H_
#define IO_SWAGGER_CLIENT_MODEL_SearchResultsCollection_H_


#include "SearchResult.h"
#include "LinkElement.h"
#include <vector>
#include "WordsApiLink.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Collection of search results.
/// </summary>
class  SearchResultsCollection
    : public LinkElement
{
public:
    SearchResultsCollection();
    virtual ~SearchResultsCollection();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SearchResultsCollection members

    /// <summary>
    /// Collection of comments
    /// </summary>
    std::vector<std::shared_ptr<SearchResult>>& getResultsList();
    bool resultsListIsSet() const;
    void unsetResultsList();
    void setResultsList(std::vector<std::shared_ptr<SearchResult>> value);

protected:
    std::vector<std::shared_ptr<SearchResult>> m_ResultsList;
    bool m_ResultsListIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_SearchResultsCollection_H_ */
