/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SectionLinkCollection.h
 *
 * Collection of links to sections
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_SectionLinkCollection_H_
#define IO_SWAGGER_CLIENT_MODEL_SectionLinkCollection_H_


#include "SectionLink.h"
#include "LinkElement.h"
#include <vector>
#include "WordsApiLink.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Collection of links to sections
/// </summary>
class  SectionLinkCollection
    : public LinkElement
{
public:
    SectionLinkCollection();
    virtual ~SectionLinkCollection();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SectionLinkCollection members

    /// <summary>
    /// Collection of section&#39;s links
    /// </summary>
    std::vector<std::shared_ptr<SectionLink>>& getSectionLinkList();
    bool sectionLinkListIsSet() const;
    void unsetSectionLinkList();
    void setSectionLinkList(std::vector<std::shared_ptr<SectionLink>> value);

protected:
    std::vector<std::shared_ptr<SectionLink>> m_SectionLinkList;
    bool m_SectionLinkListIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_SectionLinkCollection_H_ */
