/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SectionResponse.h
 *
 * This response should be returned by the service when handling: GET http://api.aspose.com/v1.1/words/Test.doc/sections/{0} 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_SectionResponse_H_
#define IO_SWAGGER_CLIENT_MODEL_SectionResponse_H_


#include "AsposeResponse.h"
#include "Section.h"
#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// This response should be returned by the service when handling: GET http://api.aspose.com/v1.1/words/Test.doc/sections/{0} 
/// </summary>
class  SectionResponse
    : public AsposeResponse
{
public:
    SectionResponse();
    virtual ~SectionResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SectionResponse members

    /// <summary>
    /// Section
    /// </summary>
    std::shared_ptr<Section> getSection() const;
    bool sectionIsSet() const;
    void unsetSection();
    void setSection(std::shared_ptr<Section> value);

protected:
    std::shared_ptr<Section> m_Section;
    bool m_SectionIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_SectionResponse_H_ */
