/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "SectionLinkCollection.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

SectionLinkCollection::SectionLinkCollection()
{
    m_SectionLinkListIsSet = false;
}

SectionLinkCollection::~SectionLinkCollection()
{
}

void SectionLinkCollection::validate()
{
    // TODO: implement validation
}

web::json::value SectionLinkCollection::toJson() const
{
    web::json::value val = this->LinkElement::toJson();

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_SectionLinkList )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[utility::conversions::to_string_t("SectionLinkList")] = web::json::value::array(jsonArray);
        }
    }

    return val;
}

void SectionLinkCollection::fromJson(web::json::value& val)
{
    this->LinkElement::fromJson(val);

    {
        m_SectionLinkList.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(utility::conversions::to_string_t("SectionLinkList")))
        {
        for( auto& item : val[utility::conversions::to_string_t("SectionLinkList")].as_array() )
        {
            if(item.is_null())
            {
                m_SectionLinkList.push_back( std::shared_ptr<SectionLink>(nullptr) );
            }
            else
            {
                std::shared_ptr<SectionLink> newItem(new SectionLink());
                newItem->fromJson(item);
                m_SectionLinkList.push_back( newItem );
            }
        }
        }
    }
}

void SectionLinkCollection::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_LinkIsSet)
    {
        if (m_Link.get())
        {
            m_Link->toMultipart(multipart, utility::conversions::to_string_t("link."));
        }
        
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_SectionLinkList )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("SectionLinkList"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
        }
    }
}

void SectionLinkCollection::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("link")))
    {
        if(multipart->hasContent(utility::conversions::to_string_t("link")))
        {
            std::shared_ptr<WordsApiLink> newItem(new WordsApiLink());
            newItem->fromMultiPart(multipart, utility::conversions::to_string_t("link."));
            setLink( newItem );
        }
    }
    {
        m_SectionLinkList.clear();
        if(multipart->hasContent(utility::conversions::to_string_t("SectionLinkList")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("SectionLinkList"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_SectionLinkList.push_back( std::shared_ptr<SectionLink>(nullptr) );
            }
            else
            {
                std::shared_ptr<SectionLink> newItem(new SectionLink());
                newItem->fromJson(item);
                m_SectionLinkList.push_back( newItem );
            }
        }
        }
    }
}

std::vector<std::shared_ptr<SectionLink>>& SectionLinkCollection::getSectionLinkList()
{
    return m_SectionLinkList;
}

void SectionLinkCollection::setSectionLinkList(std::vector<std::shared_ptr<SectionLink>> value)
{
    m_SectionLinkList = value;
    m_SectionLinkListIsSet = true;
}
bool SectionLinkCollection::sectionLinkListIsSet() const
{
    return m_SectionLinkListIsSet;
}

void SectionLinkCollection::unsetSectionLinkList()
{
    m_SectionLinkListIsSet = false;
}

}
}
}
}

