/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SplitDocumentResponse.h
 *
 * This response should be returned by the service when handling:  POST /{name}/split .
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_SplitDocumentResponse_H_
#define IO_SWAGGER_CLIENT_MODEL_SplitDocumentResponse_H_


#include "AsposeResponse.h"
#include "SplitDocumentResult.h"
#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// This response should be returned by the service when handling:  POST /{name}/split .
/// </summary>
class  SplitDocumentResponse
    : public AsposeResponse
{
public:
    SplitDocumentResponse();
    virtual ~SplitDocumentResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SplitDocumentResponse members

    /// <summary>
    /// Resylt of splitting document.
    /// </summary>
    std::shared_ptr<SplitDocumentResult> getSplitResult() const;
    bool splitResultIsSet() const;
    void unsetSplitResult();
    void setSplitResult(std::shared_ptr<SplitDocumentResult> value);

protected:
    std::shared_ptr<SplitDocumentResult> m_SplitResult;
    bool m_SplitResultIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_SplitDocumentResponse_H_ */
