/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SplitDocumentResult.h
 *
 * Result of splitting document.
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_SplitDocumentResult_H_
#define IO_SWAGGER_CLIENT_MODEL_SplitDocumentResult_H_


#include "../ModelBase.h"

#include "FileLink.h"
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Result of splitting document.
/// </summary>
class  SplitDocumentResult
    : public ModelBase
{
public:
    SplitDocumentResult();
    virtual ~SplitDocumentResult();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SplitDocumentResult members

    /// <summary>
    /// Linkt to the source document.
    /// </summary>
    std::shared_ptr<FileLink> getSourceDocument() const;
    bool sourceDocumentIsSet() const;
    void unsetSourceDocument();
    void setSourceDocument(std::shared_ptr<FileLink> value);
    /// <summary>
    /// Array of pages.
    /// </summary>
    std::vector<std::shared_ptr<FileLink>>& getPages();
    bool pagesIsSet() const;
    void unsetPages();
    void setPages(std::vector<std::shared_ptr<FileLink>> value);
    /// <summary>
    /// Link to the file archive with pages.
    /// </summary>
    std::shared_ptr<FileLink> getZippedPages() const;
    bool zippedPagesIsSet() const;
    void unsetZippedPages();
    void setZippedPages(std::shared_ptr<FileLink> value);

protected:
    std::shared_ptr<FileLink> m_SourceDocument;
    bool m_SourceDocumentIsSet;
    std::vector<std::shared_ptr<FileLink>> m_Pages;
    bool m_PagesIsSet;
    std::shared_ptr<FileLink> m_ZippedPages;
    bool m_ZippedPagesIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_SplitDocumentResult_H_ */
