/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * StatDataResponse.h
 *
 * Response for the request of the document&#39;s statistical data
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_StatDataResponse_H_
#define IO_SWAGGER_CLIENT_MODEL_StatDataResponse_H_


#include "AsposeResponse.h"
#include <cpprest/details/basic_types.h>
#include "FileLink.h"
#include "DocumentStatData.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Response for the request of the document&#39;s statistical data
/// </summary>
class  StatDataResponse
    : public AsposeResponse
{
public:
    StatDataResponse();
    virtual ~StatDataResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// StatDataResponse members

    /// <summary>
    /// Link to the document
    /// </summary>
    std::shared_ptr<FileLink> getDocumentLink() const;
    bool documentLinkIsSet() const;
    void unsetDocumentLink();
    void setDocumentLink(std::shared_ptr<FileLink> value);
    /// <summary>
    /// Statistical data of the document
    /// </summary>
    std::shared_ptr<DocumentStatData> getStatData() const;
    bool statDataIsSet() const;
    void unsetStatData();
    void setStatData(std::shared_ptr<DocumentStatData> value);

protected:
    std::shared_ptr<FileLink> m_DocumentLink;
    bool m_DocumentLinkIsSet;
    std::shared_ptr<DocumentStatData> m_StatData;
    bool m_StatDataIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_StatDataResponse_H_ */
