/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * StoryChildNodes.h
 *
 * Child nodes of  or 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_StoryChildNodes_H_
#define IO_SWAGGER_CLIENT_MODEL_StoryChildNodes_H_


#include "../ModelBase.h"

#include "NodeLink.h"
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Child nodes of  or 
/// </summary>
class  StoryChildNodes
    : public ModelBase
{
public:
    StoryChildNodes();
    virtual ~StoryChildNodes();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// StoryChildNodes members

    /// <summary>
    /// Child nodes.
    /// </summary>
    std::vector<std::shared_ptr<NodeLink>>& getChildNodes();
    bool childNodesIsSet() const;
    void unsetChildNodes();
    void setChildNodes(std::vector<std::shared_ptr<NodeLink>> value);

protected:
    std::vector<std::shared_ptr<NodeLink>> m_ChildNodes;
    bool m_ChildNodesIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_StoryChildNodes_H_ */
