/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "TablePropertiesResponse.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

TablePropertiesResponse::TablePropertiesResponse()
{
    m_PropertiesIsSet = false;
}

TablePropertiesResponse::~TablePropertiesResponse()
{
}

void TablePropertiesResponse::validate()
{
    // TODO: implement validation
}

web::json::value TablePropertiesResponse::toJson() const
{
    web::json::value val = this->AsposeResponse::toJson();

    if(m_PropertiesIsSet)
    {
        val[utility::conversions::to_string_t("Properties")] = ModelBase::toJson(m_Properties);
    }

    return val;
}

void TablePropertiesResponse::fromJson(web::json::value& val)
{
    this->AsposeResponse::fromJson(val);

    if(val.has_field(utility::conversions::to_string_t("Properties")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("Properties")];
        if(!fieldValue.is_null())
        {
            std::shared_ptr<TableProperties> newItem(new TableProperties());
            newItem->fromJson(fieldValue);
            setProperties( newItem );
        }
    }
}

void TablePropertiesResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("Code"), m_Code));
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("Status"), m_Status));
        
    }
    if(m_PropertiesIsSet)
    {
        if (m_Properties.get())
        {
            m_Properties->toMultipart(multipart, utility::conversions::to_string_t("Properties."));
        }
        
    }
}

void TablePropertiesResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setCode(ModelBase::int32_tFromHttpContent(multipart->getContent(utility::conversions::to_string_t("Code"))));
    if(multipart->hasContent(utility::conversions::to_string_t("Status")))
    {
        setStatus(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("Status"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("Properties")))
    {
        if(multipart->hasContent(utility::conversions::to_string_t("Properties")))
        {
            std::shared_ptr<TableProperties> newItem(new TableProperties());
            newItem->fromMultiPart(multipart, utility::conversions::to_string_t("Properties."));
            setProperties( newItem );
        }
    }
}

std::shared_ptr<TableProperties> TablePropertiesResponse::getProperties() const
{
    return m_Properties;
}


void TablePropertiesResponse::setProperties(std::shared_ptr<TableProperties> value)
{
    m_Properties = value;
    m_PropertiesIsSet = true;
}
bool TablePropertiesResponse::propertiesIsSet() const
{
    return m_PropertiesIsSet;
}

void TablePropertiesResponse::unsetProperties()
{
    m_PropertiesIsSet = false;
}

}
}
}
}

