/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * TableLinkCollection.h
 *
 * Collection of links to tables
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_TableLinkCollection_H_
#define IO_SWAGGER_CLIENT_MODEL_TableLinkCollection_H_


#include "TableLink.h"
#include "LinkElement.h"
#include <vector>
#include "WordsApiLink.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Collection of links to tables
/// </summary>
class  TableLinkCollection
    : public LinkElement
{
public:
    TableLinkCollection();
    virtual ~TableLinkCollection();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// TableLinkCollection members

    /// <summary>
    /// Collection of table&#39;s links
    /// </summary>
    std::vector<std::shared_ptr<TableLink>>& getTableLinkList();
    bool tableLinkListIsSet() const;
    void unsetTableLinkList();
    void setTableLinkList(std::vector<std::shared_ptr<TableLink>> value);

protected:
    std::vector<std::shared_ptr<TableLink>> m_TableLinkList;
    bool m_TableLinkListIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_TableLinkCollection_H_ */
