/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * TableCellInsert.h
 *
 * Table cell element
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_TableCellInsert_H_
#define IO_SWAGGER_CLIENT_MODEL_TableCellInsert_H_


#include "../ModelBase.h"


namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Table cell element
/// </summary>
class  TableCellInsert
    : public ModelBase
{
public:
    TableCellInsert();
    virtual ~TableCellInsert();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// TableCellInsert members

    /// <summary>
    /// Table cell will be inserted after cell with specified 0-based index.
    /// </summary>
    int32_t getInsertAfter() const;
    bool insertAfterIsSet() const;
    void unsetInsertAfter();
    void setInsertAfter(int32_t value);

protected:
    int32_t m_InsertAfter;
    bool m_InsertAfterIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_TableCellInsert_H_ */
