/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "WatermarkText.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

WatermarkText::WatermarkText()
{
    m_Text = utility::conversions::to_string_t("");
    m_TextIsSet = false;
    m_RotationAngle = 0.0;
}

WatermarkText::~WatermarkText()
{
}

void WatermarkText::validate()
{
    // TODO: implement validation
}

web::json::value WatermarkText::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_TextIsSet)
    {
        val[utility::conversions::to_string_t("Text")] = ModelBase::toJson(m_Text);
    }
    val[utility::conversions::to_string_t("RotationAngle")] = ModelBase::toJson(m_RotationAngle);

    return val;
}

void WatermarkText::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("Text")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("Text")];
        if(!fieldValue.is_null())
        {
            setText(ModelBase::stringFromJson(fieldValue));
        }
    }
    setRotationAngle(ModelBase::doubleFromJson(val[utility::conversions::to_string_t("RotationAngle")]));
}

void WatermarkText::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_TextIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("Text"), m_Text));
        
    }
    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("RotationAngle"), m_RotationAngle));
}

void WatermarkText::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("Text")))
    {
        setText(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("Text"))));
    }
    setRotationAngle(ModelBase::doubleFromHttpContent(multipart->getContent(utility::conversions::to_string_t("RotationAngle"))));
}

utility::string_t WatermarkText::getText() const
{
    return m_Text;
}


void WatermarkText::setText(utility::string_t value)
{
    m_Text = value;
    m_TextIsSet = true;
}
bool WatermarkText::textIsSet() const
{
    return m_TextIsSet;
}

void WatermarkText::unsetText()
{
    m_TextIsSet = false;
}

double WatermarkText::getRotationAngle() const
{
    return m_RotationAngle;
}


void WatermarkText::setRotationAngle(double value)
{
    m_RotationAngle = value;
    
}
}
}
}
}

