/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * WordsApiErrorResponse.h
 *
 * Response for Api error
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_WordsApiErrorResponse_H_
#define IO_SWAGGER_CLIENT_MODEL_WordsApiErrorResponse_H_


#include "AsposeResponse.h"
#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Response for Api error
/// </summary>
class  WordsApiErrorResponse
    : public AsposeResponse
{
public:
    WordsApiErrorResponse();
    virtual ~WordsApiErrorResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// WordsApiErrorResponse members

    /// <summary>
    /// Error message.
    /// </summary>
    utility::string_t getMessage() const;
    bool messageIsSet() const;
    void unsetMessage();
    void setMessage(utility::string_t value);

protected:
    utility::string_t m_Message;
    bool m_MessageIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_WordsApiErrorResponse_H_ */
