/**
 * Aspose.Words for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * XmlColor.h
 *
 * Utility class for  serialization
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_XmlColor_H_
#define IO_SWAGGER_CLIENT_MODEL_XmlColor_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Utility class for  serialization
/// </summary>
class  XmlColor
    : public ModelBase
{
public:
    XmlColor();
    virtual ~XmlColor();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// XmlColor members

    /// <summary>
    /// HTML string color representation
    /// </summary>
    utility::string_t getWeb() const;
    bool webIsSet() const;
    void unsetWeb();
    void setWeb(utility::string_t value);
    /// <summary>
    /// Alpha component of color structure
    /// </summary>
    int32_t getAlpha() const;
        void setAlpha(int32_t value);

protected:
    utility::string_t m_Web;
    bool m_WebIsSet;
    int32_t m_Alpha;
    };

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_XmlColor_H_ */
